import fonts from '@/assets/fonts';
import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';
import AuthProvider from '@/contexts/auth/AuthProvider';
import Script from 'next/script';
import '../globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.inter.className}>
        <div id="fb-root"></div>
        <div id="fb-customer-chat" className="fb-customerchat"></div>
        <AuthProvider>
          <div>
            <Header />
          </div>
          {children}
          <div>
            <Footer />
          </div>
        </AuthProvider>
      </body>
      <Script
        id="messenger-tag"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            var chatbox = document.getElementById('fb-customer-chat');
            chatbox.setAttribute("page_id", "105764165126619");
            chatbox.setAttribute("attribution", "biz_inbox");
          `,
        }}
      />
      <Script
        id="messenger-sdk"
        strategy="lazyOnload"
        dangerouslySetInnerHTML={{
          __html: `
            window.fbAsyncInit = function() {
              FB.init({
                xfbml            : true,
                version          : 'v17.0'
              });
            };
      
            (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
      `,
        }}
      />
    </html>
  );
}
